Repository ultra-supara/sisakulint, pull requests merged in 2025-02, with the labels that each got.

#118 update reporter
  .github/workflows/reviewdog.yaml
Labels: Review effort [1-5]: 1

#126 implement timeout-minutes auto fixer
  .github/workflows/reviewdog.yaml
  pkg/ast/ast_type.go
  pkg/core/autofixer.go
  pkg/core/errorformatter.go
  pkg/core/parse_sbom.go
  pkg/core/parse_sub.go
  pkg/core/timeout_minutes.go
Labels: Review effort 3/5

#130 rewrite credential hardcode password
  go.mod
  go.sum
  pkg/ast/ast_type.go
  pkg/core/autofixer.go
  pkg/core/credential.go
  pkg/core/credential.rego
  pkg/core/parse_sbom.go
  pkg/core/rego.go
  script/credential.yaml
Labels: bug, enhancement, Review effort 3/5
